apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: anubis-kafka-kill-random-leader
  namespace: strimzi-kafka
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - strimzi-kafka
    labelSelectors:
      strimzi.io/kind: "Kafka"
      strimzi.io/broker-role: "true"
  duration: "5m"