apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kafka-kill-all-pods-1
  namespace: myproject
spec:
  action: pod-kill
  mode: all
  selector:
    namespaces:
      - myproject
    labelSelectors:
      strimzi.io/kind: "Kafka"
      strimzi.io/broker-role: "true"
  duration: "5m"
