apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: zookeeper-pod-kill-example-2
  namespace: myproject
spec:
  action: pod-kill
  mode: all
  selector:
    pods:
      myproject:
        - my-cluster-zookeeper-1 # specify the pod name directly
        - my-cluster-zookeeper-2
  duration: "5m" # specify the duration for the chaos action
