apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: cluster-operator-http-chaos
spec:
  mode: all
  selector:
    labelSelectors:
      strimzi.io/kind: cluster-operator
  target: Response
  port: 8080
  method: POST
  path: '/healthy'
  abort: true
  duration: 5m
